#!/bin/sh

if [ "$GITMOJI_COMMIT" = "1" ]; then
    exit 0
fi

echo "Running gitmoji hook."

# Get most recent commit
LATEST_COMMIT=$(git rev-parse --short HEAD)

# Get the commit message of the latest commit
COMMIT_MSG=$(git log -1 --pretty=%B)

# checks for keywords and adds appropriate gitmoji
if echo "${COMMIT_MSG}" | grep -iq "performance"; then
    GITMOJI="⚡"
elif echo "${COMMIT_MSG}" | grep -iq "security"; then
    GITMOJI="🔒"
elif echo "${COMMIT_MSG}" | grep -iq "initial"; then
    GITMOJI="🎉"
elif echo "${COMMIT_MSG}" | grep -iq "documentation"; then
    GITMOJI="📝"
elif echo "${COMMIT_MSG}" | grep -iq "docs"; then
    GITMOJI="📝"
elif echo "${COMMIT_MSG}" | grep -iq "readme"; then
    GITMOJI="📝"
elif echo "${COMMIT_MSG}" | grep -iq "linting"; then
    GITMOJI="🚨"
elif echo "${COMMIT_MSG}" | grep -iq "unfinished"; then
    GITMOJI="🚧"
elif echo "${COMMIT_MSG}" | grep -iq "github"; then
    GITMOJI="💚"
elif echo "${COMMIT_MSG}" | grep -iq "workflow"; then
    GITMOJI="💚"
elif echo "${COMMIT_MSG}" | grep -iq "deployment"; then
    GITMOJI="💚"
elif echo "${COMMIT_MSG}" | grep -iq "dependencies"; then
    GITMOJI="📌"
elif echo "${COMMIT_MSG}" | grep -iq "refactor"; then
    GITMOJI="♻️"
elif echo "${COMMIT_MSG}" | grep -iq "config"; then
    GITMOJI="🔧"
elif echo "${COMMIT_MSG}" | grep -iq "revert"; then
    GITMOJI="⏪"
elif echo "${COMMIT_MSG}" | grep -iq "merge"; then
    GITMOJI="🔀"
elif echo "${COMMIT_MSG}" | grep -iq "comment"; then
    GITMOJI="💡"
elif echo "${COMMIT_MSG}" | grep -iq "logging"; then
    GITMOJI="🔊"
elif echo "${COMMIT_MSG}" | grep -iq "types"; then
    GITMOJI="🏷️"
elif echo "${COMMIT_MSG}" | grep -iq "infrastructure"; then
    GITMOJI="🧱"
elif echo "${COMMIT_MSG}" | grep -iq "deploy"; then
    GITMOJI="🚀"
elif echo "${COMMIT_MSG}" | grep -iq "critical"; then
    GITMOJI="🚑"
elif echo "${COMMIT_MSG}" | grep -iq "test"; then
    GITMOJI="🧪"
elif echo "${COMMIT_MSG}" | grep -iq "style"; then
    GITMOJI="🎨"
elif echo "${COMMIT_MSG}" | grep -iq "breaking"; then
    GITMOJI="💥"
elif echo "${COMMIT_MSG}" | grep -iq "access"; then
    GITMOJI="♿"
elif echo "${COMMIT_MSG}" | grep -iq "database"; then
    GITMOJI="🗃️"
elif echo "${COMMIT_MSG}" | grep -iq "responsive"; then
    GITMOJI="📱"
elif echo "${COMMIT_MSG}" | grep -iq "animation"; then
    GITMOJI="💫"
elif echo "${COMMIT_MSG}" | grep -iq "i18n"; then
    GITMOJI="🌐"
elif echo "${COMMIT_MSG}" | grep -iq "clean"; then
    GITMOJI="🧹"
elif echo "${COMMIT_MSG}" | grep -iq "move"; then
    GITMOJI="🚚"
elif echo "${COMMIT_MSG}" | grep -iq "improve"; then
    GITMOJI="💄"
elif echo "${COMMIT_MSG}" | grep -iq "update"; then
    GITMOJI="⬆️"
elif echo "${COMMIT_MSG}" | grep -iq "fix"; then
    GITMOJI="🐛"
elif echo "${COMMIT_MSG}" | grep -iq "add"; then
    GITMOJI="✨"
elif echo "${COMMIT_MSG}" | grep -iq "remove"; then
    GITMOJI="🔥"
else
    GITMOJI="🚀"
fi

# Amend the latest commit with the new message
GITMOJI_COMMIT=1 git commit --amend -m "$GITMOJI $COMMIT_MSG" > /dev/null

echo "Added gitmoji to commit message."
