#!/usr/bin/env python

import sys

# load the commit message from the file specified by git
commit_msg_filepath = sys.argv[1]

with open(commit_msg_filepath, 'r+') as f:
    content = f.read()
    f.seek(0, 0)
    
    if 'fix' in content:
        f.write(":bug: " + content)
    elif 'add' in content:
        f.write(":sparkles: " + content)
    elif 'remove' in content:
        f.write(":fire: " + content)
    else:
        f.write(":rocket: " + content)