#!/bin/sh

COMMIT_MSG_FILE=$1

# loads the current commit message
COMMIT_MSG=$(cat $COMMIT_MSG_FILE)

# checks for keywords and adds appropriate gitmoji
if [[ $COMMIT_MSG == *"fix"* ]]; then
    echo ":bug: $COMMIT_MSG" > $COMMIT_MSG_FILE
elif [[ $COMMIT_MSG == *"add"* ]]; then
    echo ":sparkles: $COMMIT_MSG" > $COMMIT_MSG_FILE
elif [[ $COMMIT_MSG == *"remove"* ]]; then
    echo ":fire: $COMMIT_MSG" > $COMMIT_MSG_FILE
else
    echo ":rocket: $COMMIT_MSG" > $COMMIT_MSG_FILE
fi