name: Backend Deployment to uberspace
on:
  push:
    branches:
      - 'main'
    path:
      - 'backend/**'
jobs:
  build:
    name: Build backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0