before_script:
    - apt-get update
    - apt-get install -y sshpass
    - apt-get install -y openssh-client

deploy_website:
    stage: deploy
    only:
        - master
    script:
        - cd memorandum/public
        - ls
        - tar -czf /tmp/build_website.tar.gz .
        - echo "HTMLPATH=${HTMLPATH}" > sshenv
        - sshpass -e scp -P ${SSHPORT} -r -o stricthostkeychecking=no sshenv ${SSHUSER}@${SSHHOST}:~/.ssh/environment
        - sshpass -e scp -P ${SSHPORT} -r -o stricthostkeychecking=no /tmp/build_website.tar.gz ${SSHUSER}@${SSHHOST}:${HTMLPATH}
        - sshpass -e ssh -p ${SSHPORT} -o stricthostkeychecking=no ${SSHUSER}@${SSHHOST} "cd ${HTMLPATH}; tar -zxf build_website.tar.gz"
        - sshpass -e ssh -p ${SSHPORT} -o stricthostkeychecking=no ${SSHUSER}@${SSHHOST} "cd ${HTMLPATH}; rm build_website.tar.gz"
