// Emoji keyword mappings for search (EN/DE)
export const emojiKeywords: Record<string, string[]> = {
  // Smileys & People
  '😀': ['smile', 'happy', 'lächeln', 'glücklich', 'freude'],
  '😃': ['smile', 'happy', 'big', 'lächeln', 'groß', 'fröhlich'],
  '😄': ['smile', 'laugh', 'lächeln', 'lachen'],
  '😁': ['grin', 'smile', 'grinsen', 'lächeln'],
  '😆': ['laugh', 'lol', 'lachen', 'lustig'],
  '😅': ['sweat', 'laugh', 'schweiß', 'lachen', 'nervös'],
  '🤣': ['laugh', 'rolling', 'lachen', 'lustig', 'witzig'],
  '😂': ['tears', 'laugh', 'cry', 'tränen', 'lachen', 'weinen'],
  '🙂': ['smile', 'slight', 'lächeln', 'leicht'],
  '😉': ['wink', 'zwinkern'],
  '😊': ['blush', 'smile', 'erröten', 'lächeln'],
  '😍': ['love', 'heart', 'eyes', 'liebe', 'herz', 'augen', 'verliebt'],
  '🥰': ['love', 'hearts', 'liebe', 'herzen', 'verliebt'],
  '😘': ['kiss', 'kuss', 'liebe'],
  '😎': ['cool', 'sunglasses', 'sonnenbrille'],
  '🤔': ['think', 'thinking', 'denken', 'nachdenken', 'überlegen'],
  '😴': ['sleep', 'tired', 'schlafen', 'müde'],
  '😢': ['cry', 'sad', 'weinen', 'traurig'],
  '😭': ['cry', 'sob', 'weinen', 'schluchzen', 'traurig'],
  '😡': ['angry', 'mad', 'wütend', 'sauer', 'ärger'],
  '😱': ['scream', 'shock', 'schrei', 'schock', 'angst'],
  '🤗': ['hug', 'umarmung'],
  '🤫': ['shh', 'quiet', 'psst', 'leise', 'still'],
  '🤐': ['zipper', 'quiet', 'schweigen', 'still'],
  '🤢': ['sick', 'nausea', 'krank', 'übel'],
  '🤮': ['vomit', 'sick', 'erbrechen', 'kotzen'],
  '👋': ['wave', 'hello', 'bye', 'winken', 'hallo', 'tschüss'],
  '👍': ['thumbs', 'up', 'good', 'like', 'daumen', 'hoch', 'gut'],
  '👎': ['thumbs', 'down', 'bad', 'daumen', 'runter', 'schlecht'],
  '👏': ['clap', 'applause', 'klatschen', 'applaus'],
  '🙏': ['pray', 'thanks', 'beten', 'danke', 'gebet'],
  '🤝': ['handshake', 'deal', 'händedruck', 'abmachung'],
  '✋': ['hand', 'stop', 'high five', 'hand', 'stopp'],
  '👌': ['ok', 'okay', 'perfect', 'gut', 'perfekt'],
  '✌️': ['peace', 'victory', 'frieden', 'sieg'],

  // Animals & Nature
  '🐶': ['dog', 'puppy', 'hund', 'welpe'],
  '🐱': ['cat', 'kitty', 'katze', 'kätzchen'],
  '🐭': ['mouse', 'maus'],
  '🐹': ['hamster', 'hamster'],
  '🐰': ['rabbit', 'bunny', 'hase', 'kaninchen'],
  '🦊': ['fox', 'fuchs'],
  '🐻': ['bear', 'bär'],
  '🐼': ['panda', 'panda'],
  '🐨': ['koala', 'koala'],
  '🦁': ['lion', 'löwe'],
  '🐯': ['tiger', 'tiger'],
  '🐸': ['frog', 'frosch'],
  '🐵': ['monkey', 'affe'],
  '🐔': ['chicken', 'huhn'],
  '🐧': ['penguin', 'pinguin'],
  '🐦': ['bird', 'vogel'],
  '🦆': ['duck', 'ente'],
  '🦅': ['eagle', 'adler'],
  '🦉': ['owl', 'eule'],
  '🐝': ['bee', 'biene'],
  '🦋': ['butterfly', 'schmetterling'],
  '🐌': ['snail', 'schnecke'],
  '🐞': ['ladybug', 'marienkäfer'],
  '🐢': ['turtle', 'schildkröte'],
  '🐍': ['snake', 'schlange'],
  '🐙': ['octopus', 'tintenfisch', 'krake'],
  '🐠': ['fish', 'tropical', 'fisch', 'tropisch'],
  '🐬': ['dolphin', 'delfin'],
  '🦈': ['shark', 'hai'],
  '🐘': ['elephant', 'elefant'],
  '🦒': ['giraffe', 'giraffe'],
  '🦘': ['kangaroo', 'känguru'],
  '🐎': ['horse', 'pferd'],
  '🦄': ['unicorn', 'einhorn'],
  '🌵': ['cactus', 'kaktus'],
  '🌲': ['tree', 'evergreen', 'baum', 'tanne'],
  '🌳': ['tree', 'baum'],
  '🌴': ['palm', 'tree', 'palme', 'baum'],
  '🌱': ['plant', 'seedling', 'pflanze', 'setzling'],
  '🌹': ['rose', 'flower', 'rose', 'blume'],
  '🌺': ['hibiscus', 'flower', 'hibiskus', 'blume'],
  '🌻': ['sunflower', 'sonnenblume'],
  '🌼': ['flower', 'blossom', 'blume', 'blüte'],
  '🌷': ['tulip', 'tulpe'],
  '🍄': ['mushroom', 'pilz'],
  '🌍': ['earth', 'world', 'globe', 'erde', 'welt', 'globus'],
  '🌎': ['earth', 'world', 'globe', 'americas', 'erde', 'welt', 'amerika'],
  '🌏': ['earth', 'world', 'globe', 'asia', 'erde', 'welt', 'asien'],
  '⭐': ['star', 'stern'],
  '🌟': ['star', 'glowing', 'stern', 'leuchtend'],
  '✨': ['sparkles', 'shine', 'funkeln', 'glitzer'],
  '🔥': ['fire', 'hot', 'feuer', 'heiß', 'flamme'],
  '💧': ['water', 'drop', 'wasser', 'tropfen'],
  '🌊': ['wave', 'ocean', 'sea', 'welle', 'ozean', 'meer'],
  '☀️': ['sun', 'sunny', 'sonne', 'sonnig'],
  '🌙': ['moon', 'crescent', 'mond', 'sichel'],
  '🌈': ['rainbow', 'regenbogen'],
  '☁️': ['cloud', 'wolke'],
  '⚡': ['lightning', 'bolt', 'blitz'],
  '❄️': ['snow', 'snowflake', 'schnee', 'schneeflocke'],

  // Food & Drink
  '🍏': ['apple', 'green', 'apfel', 'grün'],
  '🍎': ['apple', 'red', 'apfel', 'rot'],
  '🍊': ['orange', 'orange', 'apfelsine'],
  '🍋': ['lemon', 'zitrone'],
  '🍌': ['banana', 'banane'],
  '🍉': ['watermelon', 'wassermelone'],
  '🍇': ['grapes', 'trauben', 'weintrauben'],
  '🍓': ['strawberry', 'erdbeere'],
  '🍒': ['cherry', 'cherries', 'kirsche', 'kirschen'],
  '🍑': ['peach', 'pfirsich'],
  '🥝': ['kiwi', 'kiwi'],
  '🍅': ['tomato', 'tomate'],
  '🥑': ['avocado', 'avocado'],
  '🥦': ['broccoli', 'brokkoli'],
  '🥕': ['carrot', 'karotte', 'möhre'],
  '🌽': ['corn', 'mais'],
  '🍞': ['bread', 'brot'],
  '🥖': ['baguette', 'bread', 'baguette', 'brot'],
  '🧀': ['cheese', 'käse'],
  '🥚': ['egg', 'ei'],
  '🍳': ['cooking', 'egg', 'fried', 'kochen', 'ei', 'gebraten'],
  '🥓': ['bacon', 'speck'],
  '🍔': ['burger', 'hamburger', 'burger', 'hamburger'],
  '🍟': ['fries', 'pommes'],
  '🍕': ['pizza', 'pizza'],
  '🌭': ['hot dog', 'hotdog'],
  '🥪': ['sandwich', 'sandwich'],
  '🌮': ['taco', 'taco'],
  '🌯': ['burrito', 'wrap', 'burrito'],
  '🍝': ['pasta', 'spaghetti', 'pasta', 'nudeln'],
  '🍜': ['ramen', 'noodles', 'ramen', 'nudeln'],
  '🍣': ['sushi', 'sushi'],
  '🍱': ['bento', 'box', 'bento'],
  '🍛': ['curry', 'rice', 'curry', 'reis'],
  '🍦': ['ice cream', 'eis', 'eiscreme'],
  '🍰': ['cake', 'kuchen', 'torte'],
  '🎂': ['birthday', 'cake', 'geburtstag', 'kuchen', 'torte'],
  '🍪': ['cookie', 'keks'],
  '🍩': ['donut', 'doughnut', 'donut', 'krapfen'],
  '🍫': ['chocolate', 'schokolade'],
  '🍬': ['candy', 'sweet', 'süßigkeit', 'bonbon'],
  '🍭': ['lollipop', 'lutscher'],
  '☕': ['coffee', 'tea', 'kaffee', 'tee'],
  '🍵': ['tea', 'green', 'tee', 'grün'],
  '🍺': ['beer', 'bier'],
  '🍻': ['beers', 'cheers', 'bier', 'prost', 'anstoßen'],
  '🍷': ['wine', 'wein'],
  '🥂': ['champagne', 'cheers', 'sekt', 'champagner', 'prost'],
  '🍹': ['cocktail', 'tropical', 'cocktail', 'drink'],

  // Activities & Objects
  '⚽': ['soccer', 'football', 'fußball'],
  '🏀': ['basketball', 'basketball'],
  '🏈': ['football', 'american', 'football', 'amerikanisch'],
  '⚾': ['baseball', 'baseball'],
  '🎾': ['tennis', 'tennis'],
  '🏐': ['volleyball', 'volleyball'],
  '🎱': ['billiard', 'pool', 'billard'],
  '🎮': ['game', 'controller', 'spiel', 'controller', 'gaming'],
  '🎯': ['target', 'dart', 'ziel', 'dart', 'darts'],
  '🎲': ['dice', 'würfel'],
  '🎭': ['theater', 'drama', 'theater', 'drama', 'maske'],
  '🎨': ['art', 'palette', 'kunst', 'palette', 'malen'],
  '🎬': ['movie', 'film', 'kino'],
  '🎤': ['microphone', 'sing', 'mikrofon', 'singen'],
  '🎧': ['headphones', 'music', 'kopfhörer', 'musik'],
  '🎸': ['guitar', 'gitarre'],
  '🎹': ['piano', 'keyboard', 'klavier'],
  '🥁': ['drum', 'trommel', 'schlagzeug'],
  '📱': ['phone', 'mobile', 'smartphone', 'handy', 'telefon'],
  '💻': ['computer', 'laptop', 'pc', 'computer', 'laptop'],
  '⌨️': ['keyboard', 'tastatur'],
  '🖥': ['computer', 'desktop', 'monitor', 'computer', 'bildschirm'],
  '🖨': ['printer', 'drucker'],
  '🖱': ['mouse', 'computer', 'maus', 'computer'],
  '📷': ['camera', 'photo', 'kamera', 'foto'],
  '📸': ['camera', 'flash', 'kamera', 'blitz', 'foto'],
  '📺': ['tv', 'television', 'fernseher'],
  '⏰': ['alarm', 'clock', 'wecker', 'uhr'],
  '⏱': ['stopwatch', 'stoppuhr'],
  '⌛': ['hourglass', 'time', 'sanduhr', 'zeit'],
  '💡': ['light', 'bulb', 'idea', 'licht', 'birne', 'idee'],
  '🔦': ['flashlight', 'torch', 'taschenlampe'],
  '🔋': ['battery', 'batterie', 'akku'],
  '💰': ['money', 'bag', 'geld', 'sack', 'reich'],
  '💵': ['dollar', 'money', 'dollar', 'geld'],
  '💶': ['euro', 'money', 'euro', 'geld'],
  '💳': ['card', 'credit', 'karte', 'kredit'],
  '💎': ['diamond', 'gem', 'diamant', 'edelstein'],
  '🔧': ['wrench', 'tool', 'schraubenschlüssel', 'werkzeug'],
  '🔨': ['hammer', 'tool', 'hammer', 'werkzeug'],
  '🔩': ['nut', 'bolt', 'mutter', 'schraube'],
  '⚙️': ['gear', 'settings', 'zahnrad', 'einstellungen'],
  '🔒': ['lock', 'secure', 'schloss', 'sicher'],
  '🔑': ['key', 'schlüssel'],
  '🎁': ['gift', 'present', 'geschenk', 'präsent'],
  '🎈': ['balloon', 'luftballon'],
  '🎉': ['party', 'celebration', 'party', 'feier', 'konfetti'],
  '🎊': ['confetti', 'celebration', 'konfetti', 'feier'],
  '🏆': ['trophy', 'winner', 'pokal', 'gewinner', 'sieg'],
  '🥇': ['gold', 'medal', 'first', 'gold', 'medaille', 'erster'],
  '🥈': ['silver', 'medal', 'second', 'silber', 'medaille', 'zweiter'],
  '🥉': ['bronze', 'medal', 'third', 'bronze', 'medaille', 'dritter'],

  // Travel & Places
  '🚗': ['car', 'auto', 'fahren'],
  '🚕': ['taxi', 'taxi'],
  '🚙': ['suv', 'car', 'auto'],
  '🚌': ['bus', 'bus'],
  '🚎': ['trolleybus', 'bus', 'bus'],
  '🚓': ['police', 'car', 'polizei', 'auto'],
  '🚑': ['ambulance', 'krankenwagen', 'rettung'],
  '🚒': ['fire', 'truck', 'feuerwehr'],
  '🚚': ['truck', 'delivery', 'lkw', 'lastwagen', 'lieferung'],
  '🚲': ['bike', 'bicycle', 'fahrrad', 'rad'],
  '🛵': ['scooter', 'moped', 'roller'],
  '🏍': ['motorcycle', 'motorrad'],
  '✈️': ['airplane', 'plane', 'flight', 'flugzeug', 'fliegen', 'flug'],
  '🚀': ['rocket', 'space', 'rakete', 'weltraum'],
  '🚁': ['helicopter', 'hubschrauber'],
  '⛵': ['sailboat', 'boat', 'segelboot', 'boot'],
  '🚢': ['ship', 'cruise', 'schiff', 'kreuzfahrt'],
  '🏠': ['house', 'home', 'haus', 'zuhause'],
  '🏡': ['house', 'garden', 'haus', 'garten'],
  '🏢': ['office', 'building', 'büro', 'gebäude'],
  '🏥': ['hospital', 'krankenhaus'],
  '🏦': ['bank', 'bank'],
  '🏪': ['store', 'shop', 'laden', 'geschäft'],
  '🏫': ['school', 'schule'],
  '🏨': ['hotel', 'hotel'],
  '⛪': ['church', 'kirche'],
  '🗼': ['tower', 'tokyo', 'turm'],
  '🗽': ['statue', 'liberty', 'freiheitsstatue'],
  '🏖': ['beach', 'strand'],
  '🏝': ['island', 'insel'],
  '⛰': ['mountain', 'berg'],
  '🏔': ['mountain', 'snow', 'berg', 'schnee'],
  '🌋': ['volcano', 'vulkan'],
  '🏕': ['camping', 'camp', 'zelten', 'camping'],
  '⛺': ['tent', 'camping', 'zelt', 'zelten'],

  // Symbols
  '❤️': ['heart', 'love', 'herz', 'liebe'],
  '🧡': ['heart', 'orange', 'herz', 'orange'],
  '💛': ['heart', 'yellow', 'herz', 'gelb'],
  '💚': ['heart', 'green', 'herz', 'grün'],
  '💙': ['heart', 'blue', 'herz', 'blau'],
  '💜': ['heart', 'purple', 'herz', 'lila', 'violett'],
  '🖤': ['heart', 'black', 'herz', 'schwarz'],
  '🤍': ['heart', 'white', 'herz', 'weiß'],
  '💔': ['broken', 'heart', 'gebrochenes', 'herz'],
  '💕': ['hearts', 'love', 'herzen', 'liebe'],
  '💯': ['hundred', 'perfect', 'hundert', 'perfekt'],
  '💢': ['anger', 'angry', 'wut', 'wütend', 'ärger'],
  '✅': ['check', 'done', 'yes', 'haken', 'fertig', 'ja'],
  '❌': ['x', 'cross', 'no', 'kreuz', 'nein'],
  '⭕': ['circle', 'o', 'kreis'],
  '❗': ['exclamation', 'important', 'ausrufezeichen', 'wichtig'],
  '❓': ['question', 'frage'],
  '⚠️': ['warning', 'warnung'],
  '🚫': ['prohibited', 'no', 'verboten', 'nein'],
  '✔️': ['check', 'yes', 'haken', 'ja'],
  '🔴': ['red', 'circle', 'rot', 'kreis'],
  '🟢': ['green', 'circle', 'grün', 'kreis'],
  '🔵': ['blue', 'circle', 'blau', 'kreis'],
  '🟡': ['yellow', 'circle', 'gelb', 'kreis'],
  '🟠': ['orange', 'circle', 'orange', 'kreis'],
  '🟣': ['purple', 'circle', 'lila', 'kreis', 'violett'],
  '⚪': ['white', 'circle', 'weiß', 'kreis'],
  '⚫': ['black', 'circle', 'schwarz', 'kreis'],
  '➕': ['plus', 'add', 'plus', 'hinzufügen'],
  '➖': ['minus', 'subtract', 'minus', 'abziehen'],
  '✖️': ['multiply', 'x', 'multiplizieren', 'mal'],
  '➗': ['divide', 'dividieren', 'teilen'],
  '🔢': ['numbers', 'zahlen'],
  '🔤': ['letters', 'abc', 'buchstaben'],
  '🆕': ['new', 'neu'],
  '🆒': ['cool', 'cool'],
  '🆓': ['free', 'kostenlos', 'frei'],
  '🆙': ['up', 'level up', 'hoch', 'aufsteigen'],
  '🆗': ['ok', 'okay', 'ok'],

  // Flags
  '🏁': ['checkered', 'flag', 'racing', 'zielflagge', 'rennen'],
  '🚩': ['flag', 'red', 'flagge', 'rot'],
  '🏳️': ['white', 'flag', 'weiße', 'flagge'],
  '🏳️‍🌈': ['rainbow', 'flag', 'pride', 'regenbogen', 'flagge'],
};

export type EmojiCategory = {
  name: string;
  emojis: string[];
};

export const emojiCategories: EmojiCategory[] = [
  {
    name: 'Smileys & People',
    emojis: [
      '😀',
      '😃',
      '😄',
      '😁',
      '😆',
      '😅',
      '🤣',
      '😂',
      '🙂',
      '🙃',
      '😉',
      '😊',
      '😇',
      '🥰',
      '😍',
      '🤩',
      '😘',
      '😗',
      '😚',
      '😙',
      '😋',
      '😛',
      '😜',
      '🤪',
      '😝',
      '🤑',
      '🤗',
      '🤭',
      '🤫',
      '🤔',
      '🤐',
      '🤨',
      '😐',
      '😑',
      '😶',
      '😏',
      '😒',
      '🙄',
      '😬',
      '🤥',
      '😌',
      '😔',
      '😪',
      '🤤',
      '😴',
      '😷',
      '🤒',
      '🤕',
      '🤢',
      '🤮',
      '🤧',
      '🥵',
      '🥶',
      '😎',
      '🤓',
      '🧐',
      '😕',
      '😟',
      '🙁',
      '☹️',
      '😮',
      '😯',
      '😲',
      '😳',
      '🥺',
      '😦',
      '😧',
      '😨',
      '😰',
      '😥',
      '😢',
      '😭',
      '😱',
      '😖',
      '😣',
      '😞',
      '😓',
      '😩',
      '😫',
      '🥱',
      '😤',
      '😡',
      '😠',
      '🤬',
      '👋',
      '🤚',
      '✋',
      '🖐',
      '👌',
      '🤏',
      '✌️',
      '🤞',
      '🤟',
      '🤘',
      '🤙',
      '👈',
      '👉',
      '👆',
      '👇',
      '☝️',
      '👍',
      '👎',
      '✊',
      '👊',
      '🤛',
      '🤜',
      '👏',
      '🙌',
      '👐',
      '🤲',
      '🤝',
      '🙏',
    ],
  },
  {
    name: 'Animals & Nature',
    emojis: [
      '🐶',
      '🐱',
      '🐭',
      '🐹',
      '🐰',
      '🦊',
      '🐻',
      '🐼',
      '🐨',
      '🐯',
      '🦁',
      '🐮',
      '🐷',
      '🐸',
      '🐵',
      '🐔',
      '🐧',
      '🐦',
      '🐤',
      '🦆',
      '🦅',
      '🦉',
      '🦇',
      '🐺',
      '🐗',
      '🐴',
      '🦄',
      '🐝',
      '🐛',
      '🦋',
      '🐌',
      '🐞',
      '🐜',
      '🦟',
      '🦗',
      '🕷',
      '🦂',
      '🐢',
      '🐍',
      '🦎',
      '🦖',
      '🦕',
      '🐙',
      '🦑',
      '🦐',
      '🦞',
      '🦀',
      '🐡',
      '🐠',
      '🐟',
      '🐬',
      '🐳',
      '🐋',
      '🦈',
      '🐊',
      '🐅',
      '🐆',
      '🦓',
      '🦍',
      '🦧',
      '🐘',
      '🦛',
      '🦏',
      '🐪',
      '🐫',
      '🦒',
      '🦘',
      '🐃',
      '🐂',
      '🐄',
      '🐎',
      '🐖',
      '🐏',
      '🐑',
      '🦙',
      '🐐',
      '🦌',
      '🐕',
      '🐩',
      '🦮',
      '🐈',
      '🐓',
      '🦃',
      '🦚',
      '🦜',
      '🦢',
      '🦩',
      '🕊',
      '🐇',
      '🦝',
      '🦨',
      '🦡',
      '🦦',
      '🦥',
      '🐁',
      '🐀',
      '🐿',
      '🦔',
      '🌵',
      '🎄',
      '🌲',
      '🌳',
      '🌴',
      '🌱',
      '🌿',
      '☘️',
      '🍀',
      '🎍',
      '🎋',
      '🍃',
      '🍂',
      '🍁',
      '🌾',
      '🌺',
      '🌻',
      '🌹',
      '🥀',
      '🌷',
      '🌼',
      '🌸',
      '💐',
      '🍄',
      '🌰',
      '🦀',
      '🐚',
      '🌍',
      '🌎',
      '🌏',
      '🌕',
      '🌖',
      '🌗',
      '🌘',
      '🌑',
      '🌒',
      '🌓',
      '🌔',
      '🌙',
      '🌚',
      '🌛',
      '🌜',
      '☀️',
      '🌝',
      '🌞',
      '⭐',
      '🌟',
      '💫',
      '✨',
      '☄️',
      '🌠',
      '🌌',
      '☁️',
      '⛅',
      '⛈',
      '🌤',
      '🌥',
      '🌦',
      '🌧',
      '🌨',
      '🌩',
      '🌪',
      '🌫',
      '🌬',
      '🌀',
      '🌈',
      '🌂',
      '☂️',
      '☔',
      '⛱',
      '⚡',
      '❄️',
      '☃️',
      '⛄',
      '☄️',
      '🔥',
      '💧',
      '🌊',
    ],
  },
  {
    name: 'Food & Drink',
    emojis: [
      '🍏',
      '🍎',
      '🍐',
      '🍊',
      '🍋',
      '🍌',
      '🍉',
      '🍇',
      '🍓',
      '🍈',
      '🍒',
      '🍑',
      '🥭',
      '🍍',
      '🥥',
      '🥝',
      '🍅',
      '🍆',
      '🥑',
      '🥦',
      '🥬',
      '🥒',
      '🌶',
      '🌽',
      '🥕',
      '🥔',
      '🍠',
      '🥐',
      '🥯',
      '🍞',
      '🥖',
      '🥨',
      '🧀',
      '🥚',
      '🍳',
      '🥞',
      '🥓',
      '🥩',
      '🍗',
      '🍖',
      '🌭',
      '🍔',
      '🍟',
      '🍕',
      '🥪',
      '🥙',
      '🌮',
      '🌯',
      '🥗',
      '🥘',
      '🥫',
      '🍝',
      '🍜',
      '🍲',
      '🍛',
      '🍣',
      '🍱',
      '🥟',
      '🍤',
      '🍙',
      '🍚',
      '🍘',
      '🍥',
      '🥠',
      '🥮',
      '🍢',
      '🍡',
      '🍧',
      '🍨',
      '🍦',
      '🥧',
      '🧁',
      '🍰',
      '🎂',
      '🍮',
      '🍭',
      '🍬',
      '🍫',
      '🍿',
      '🍩',
      '🍪',
      '🌰',
      '🥜',
      '🍯',
      '🥛',
      '🍼',
      '☕',
      '🍵',
      '🥤',
      '🍶',
      '🍺',
      '🍻',
      '🥂',
      '🍷',
      '🥃',
      '🍸',
      '🍹',
      '🍾',
      '🥄',
      '🍴',
      '🍽',
    ],
  },
  {
    name: 'Activities & Objects',
    emojis: [
      '⚽',
      '🏀',
      '🏈',
      '⚾',
      '🥎',
      '🎾',
      '🏐',
      '🏉',
      '🥏',
      '🎱',
      '🏓',
      '🏸',
      '🏒',
      '🏑',
      '🥍',
      '🏏',
      '🥅',
      '⛳',
      '🏹',
      '🎣',
      '🥊',
      '🥋',
      '🎽',
      '⛸',
      '🥌',
      '🛷',
      '🎿',
      '⛷',
      '🏂',
      '🏋️',
      '🤼',
      '🤸',
      '🤺',
      '🤾',
      '🏌️',
      '🏇',
      '🧘',
      '🏊',
      '🤽',
      '🚣',
      '🧗',
      '🚴',
      '🚵',
      '🎪',
      '🎭',
      '🎨',
      '🎬',
      '🎤',
      '🎧',
      '🎼',
      '🎹',
      '🥁',
      '🎷',
      '🎺',
      '🎸',
      '🎻',
      '🎲',
      '♟',
      '🎯',
      '🎳',
      '🎮',
      '🎰',
      '🧩',
      '📱',
      '💻',
      '⌨️',
      '🖥',
      '🖨',
      '🖱',
      '🖲',
      '🕹',
      '💾',
      '💿',
      '📀',
      '📼',
      '📷',
      '📸',
      '📹',
      '🎥',
      '📽',
      '🎞',
      '📞',
      '☎️',
      '📟',
      '📠',
      '📺',
      '📻',
      '🎙',
      '🎚',
      '🎛',
      '⏱',
      '⏲',
      '⏰',
      '🕰',
      '⌛',
      '⏳',
      '📡',
      '🔋',
      '🔌',
      '💡',
      '🔦',
      '🕯',
      '🧯',
      '🛢',
      '💸',
      '💵',
      '💴',
      '💶',
      '💷',
      '💰',
      '💳',
      '💎',
      '⚖️',
      '🧰',
      '🔧',
      '🔨',
      '⚒',
      '🛠',
      '⛏',
      '🔩',
      '⚙️',
      '🧱',
      '⛓',
      '🧲',
      '🔫',
      '💣',
      '🧨',
      '🔪',
      '🗡',
      '⚔️',
      '🛡',
      '🚬',
      '⚰️',
      '⚱️',
      '🏺',
      '🔮',
      '📿',
      '💈',
      '⚗️',
      '🔭',
      '🔬',
      '🕳',
      '💊',
      '💉',
      '🩸',
      '🩹',
      '🩺',
      '🌡',
      '🏷',
      '🔖',
      '🚽',
      '🚿',
      '🛁',
      '🛀',
      '🧴',
      '🧷',
      '🧹',
      '🧺',
      '🧻',
      '🧼',
      '🧽',
      '🧯',
      '🛒',
    ],
  },
  {
    name: 'Travel & Places',
    emojis: [
      '🚗',
      '🚕',
      '🚙',
      '🚌',
      '🚎',
      '🏎',
      '🚓',
      '🚑',
      '🚒',
      '🚐',
      '🚚',
      '🚛',
      '🚜',
      '🛴',
      '🚲',
      '🛵',
      '🏍',
      '🛺',
      '🚨',
      '🚔',
      '🚍',
      '🚘',
      '🚖',
      '🚡',
      '🚠',
      '🚟',
      '🚃',
      '🚋',
      '🚞',
      '🚝',
      '🚄',
      '🚅',
      '🚈',
      '🚂',
      '🚆',
      '🚇',
      '🚊',
      '🚉',
      '✈️',
      '🛫',
      '🛬',
      '🛩',
      '💺',
      '🛰',
      '🚀',
      '🛸',
      '🚁',
      '🛶',
      '⛵',
      '🚤',
      '🛥',
      '🛳',
      '⛴',
      '🚢',
      '⚓',
      '⛽',
      '🚧',
      '🚦',
      '🚥',
      '🗺',
      '🗿',
      '🗽',
      '🗼',
      '🏰',
      '🏯',
      '🏟',
      '🎡',
      '🎢',
      '🎠',
      '⛲',
      '⛱',
      '🏖',
      '🏝',
      '🏜',
      '🌋',
      '⛰',
      '🏔',
      '🗻',
      '🏕',
      '⛺',
      '🏠',
      '🏡',
      '🏘',
      '🏚',
      '🏗',
      '🏭',
      '🏢',
      '🏬',
      '🏣',
      '🏤',
      '🏥',
      '🏦',
      '🏨',
      '🏪',
      '🏫',
      '🏩',
      '💒',
      '🏛',
      '⛪',
      '🕌',
      '🕍',
      '🛕',
      '🕋',
      '⛩',
      '🛤',
      '🛣',
      '🗾',
      '🎑',
      '🏞',
      '🌅',
      '🌄',
      '🌠',
      '🎇',
      '🎆',
      '🌇',
      '🌆',
      '🏙',
      '🌃',
      '🌌',
      '🌉',
      '🌁',
    ],
  },
  {
    name: 'Symbols',
    emojis: [
      '❤️',
      '🧡',
      '💛',
      '💚',
      '💙',
      '💜',
      '🖤',
      '🤍',
      '🤎',
      '💔',
      '❣️',
      '💕',
      '💞',
      '💓',
      '💗',
      '💖',
      '💘',
      '💝',
      '💟',
      '☮️',
      '✝️',
      '☪️',
      '🕉',
      '☸️',
      '✡️',
      '🔯',
      '🕎',
      '☯️',
      '☦️',
      '🛐',
      '⛎',
      '♈',
      '♉',
      '♊',
      '♋',
      '♌',
      '♍',
      '♎',
      '♏',
      '♐',
      '♑',
      '♒',
      '♓',
      '🆔',
      '⚛️',
      '🉑',
      '☢️',
      '☣️',
      '📴',
      '📳',
      '🈶',
      '🈚',
      '🈸',
      '🈺',
      '🈷️',
      '✴️',
      '🆚',
      '💮',
      '🉐',
      '㊙️',
      '㊗️',
      '🈴',
      '🈵',
      '🈹',
      '🈲',
      '🅰️',
      '🅱️',
      '🆎',
      '🆑',
      '🅾️',
      '🆘',
      '❌',
      '⭕',
      '🛑',
      '⛔',
      '📛',
      '🚫',
      '💯',
      '💢',
      '♨️',
      '🚷',
      '🚯',
      '🚳',
      '🚱',
      '🔞',
      '📵',
      '🚭',
      '❗',
      '❕',
      '❓',
      '❔',
      '‼️',
      '⁉️',
      '🔅',
      '🔆',
      '〽️',
      '⚠️',
      '🚸',
      '🔱',
      '⚜️',
      '🔰',
      '♻️',
      '✅',
      '🈯',
      '💹',
      '❇️',
      '✳️',
      '❎',
      '🌐',
      '💠',
      'Ⓜ️',
      '🌀',
      '💤',
      '🏧',
      '🚾',
      '♿',
      '🅿️',
      '🈳',
      '🈂️',
      '🛂',
      '🛃',
      '🛄',
      '🛅',
      '🚹',
      '🚺',
      '🚼',
      '🚻',
      '🚮',
      '🎦',
      '📶',
      '🈁',
      '🔣',
      'ℹ️',
      '🔤',
      '🔡',
      '🔠',
      '🆖',
      '🆗',
      '🆙',
      '🆒',
      '🆕',
      '🆓',
      '0️⃣',
      '1️⃣',
      '2️⃣',
      '3️⃣',
      '4️⃣',
      '5️⃣',
      '6️⃣',
      '7️⃣',
      '8️⃣',
      '9️⃣',
      '🔟',
      '🔢',
      '#️⃣',
      '*️⃣',
      '⏏️',
      '▶️',
      '⏸',
      '⏯',
      '⏹',
      '⏺',
      '⏭',
      '⏮',
      '⏩',
      '⏪',
      '⏫',
      '⏬',
      '◀️',
      '🔼',
      '🔽',
      '➡️',
      '⬅️',
      '⬆️',
      '⬇️',
      '↗️',
      '↘️',
      '↙️',
      '↖️',
      '↕️',
      '↔️',
      '↪️',
      '↩️',
      '⤴️',
      '⤵️',
      '🔀',
      '🔁',
      '🔂',
      '🔄',
      '🔃',
      '🎵',
      '🎶',
      '➕',
      '➖',
      '➗',
      '✖️',
      '♾',
      '💲',
      '💱',
      '™️',
      '©️',
      '®️',
      '〰️',
      '➰',
      '➿',
      '🔚',
      '🔙',
      '🔛',
      '🔝',
      '🔜',
      '✔️',
      '☑️',
      '🔘',
      '⚪',
      '⚫',
      '🔴',
      '🟠',
      '🟡',
      '🟢',
      '🔵',
      '🟣',
      '🟤',
      '⭐',
      '🌟',
      '💫',
      '✨',
      '🔥',
      '💥',
      '💯',
      '💢',
      '💬',
      '👁️‍🗨️',
      '🗨',
      '🗯',
      '💭',
      '💤',
    ],
  },
  {
    name: 'Flags',
    emojis: [
      '🏁',
      '🚩',
      '🎌',
      '🏴',
      '🏳️',
      '🏳️‍🌈',
      '🏳️‍⚧️',
      '🏴‍☠️',
    ],
  },
];
