name: Backend Deployment to uberspace
on:
  push:
    branches:
      - 'main'
    paths:
      - 'backend/**'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Testing Frontend
        run: echo "Testing..."      

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Building Frontend
        run: echo "Building..."

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploying Frontend
        run: echo "Deploying..."    