name: Frontend  Deployment to uberspace
on:
  push:
    branches:
      - "main"
    paths:
      - "frontend/**"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Testing Frontend
        run: echo "Testing not implemented yet..."

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Building Frontend
        run: echo "Building svelte application..."

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 20.11.1 LTS version
        uses: actions/setup-node@v2
        with:
          node-version: 20.11.1

      - name: Cache node_modules
        id: node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules

      - name: Npm clean install
        run: |
          cd frontend
          npm ci

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Zip frontend
        run: |
          cd frontend
          zip -r dist.zip dist

      - name: Upload zipped frontend artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: frontend/dist.zip

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploying Frontend
        run: echo "Deploying frontend artifact..."

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: frontend

      - name: Unzip frontend to target directory
        run: |
          mkdir -p frontend_target
          unzip frontend/dist.zip -d frontend_temp
          mv frontend_temp/dist/* frontend_target/
          rm -rf frontend_temp

      - name: Recursivly upload built frontend files to uberspace
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.SSHHOST }}
          username: ${{ secrets.SSHUSER }}
          password: ${{ secrets.SSHPASS }}
          port: ${{ vars.SSHPORT }}
          source: "frontend_target/*"
          target: /var/www/virtual/${{ secrets.SSHUSER }}/html
          overwrite: true

      - name: SSH into the remote server and move files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSHHOST }}
          username: ${{ secrets.SSHUSER }}
          password: ${{ secrets.SSHPASS }}
          port: ${{ vars.SSHPORT }}
          script: |
            cp -rf html/frontend_target/. html/
            rm -rf html/frontend_target
