name: Frontend  Deployment to uberspace
on:
  push:
    branches:
      - "main"
    paths:
      - "frontend/**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Testing Frontend
        run: echo "Testing not implemented yet..."

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Building Frontend
        run: echo "Building svelte application..."

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20.11.1 LTS version
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1

      - name: Cache node_modules
        id: node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules

      - name: Debug cache hit
        run: echo ${{ steps.node_modules.outputs.cache-hit }}

      - name: Npm install
        if: steps.node_modules.outputs.cache-hit != 'true' # Skip if cache hit
        run: |
          cd frontend
          npm i --legacy-peer-deps

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Zip frontend
        run: |
          cd frontend
          zip -r dist.zip dist

      - name: Upload zipped frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: frontend/dist.zip

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploying Frontend
        run: echo "Deploying frontend artifact..."

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: frontend

      - name: Unzip frontend to target directory
        run: |
          mkdir -p frontend_target
          unzip frontend/dist.zip -d frontend_temp
          mv frontend_temp/dist/* frontend_target/
          rm -rf frontend_temp

      - name: Recursivly upload built frontend files to uberspace
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSHHOST }}
          username: ${{ secrets.SSHUSER }}
          password: ${{ secrets.SSHPASS }}
          port: ${{ secrets.SSHPORT }}
          source: "frontend_target/*"
          target: /var/www/virtual/${{ secrets.SSHUSER }}/html
          overwrite: true

      - name: SSH into the remote server and move files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSHHOST }}
          username: ${{ secrets.SSHUSER }}
          password: ${{ secrets.SSHPASS }}
          port: ${{ secrets.SSHPORT }}
          script: |
            cp -rf html/frontend_target/. html/
            rm -rf html/frontend_target
