name: renovate

on:
  push:
    branches: [issue/renovate-test]

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      LOG_LEVEL: debug
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.3
        with:
          configurationFile: renovate.json
          # token: ${{ secrets.CI_TOKEN }}
